export const extensionIconPaths: Record<string, string> = {
  // ** File icons
  tsx: "/icons/react_ts",
  js: "/icons/javascript",
  json: "/icons/json",
  jsx: "/icons/react",
  svg: "/icons/svg",
  html: "/icons/html",
  ts: "/icons/typescript",
  gitignore: "/icons/git",
  md: "/icons/readme",
  png: "/icons/image",
  ico: "/icons/image",
  css: "/icons/css",

  // ** Folder icons
  node_modules: "/icons/folder-node",
  public: "/icons/folder-public",
  src: "/icons/folder-src",
  styles: "/icons/folder-css",
  assets: "/icons/folder-images",
  components: "/icons/folder-components",
  pages: "/icons/folder-packages",
  data: "/icons/folder-data",
  utils: "/icons/folder-utils",
  context: "/icons/folder-context",
  hooks: "/icons/folder-hook",
  layouts: "/icons/folder-layout",
  redux: "/icons/folder-redux-selector",
  routes: "/icons/folder-routes",
  services: "/icons/folder-config",
  admin: "/icons/folder-admin",
  themes: "/icons/folder-theme",
};